#LinkNode-cli
SOURCES_LINKNODE = /home/krupesh/DataStructures/LinkNodes_example/LinkNode.cpp
OBJECTS_LINKNODE = $(SOURCES_LINKNODE:.cpp = .o)
EXECUTABLE_LINKNODE = LinkNode-cli
$(EXECUTABLE_LINKNODE):
	g++ $(OBJECTS_LINKNODE) -o build/$@


#LinkedList-cli
SOURCES_LNKEDLIST = /home/krupesh/DataStructures/LinkedList/main.cpp
OBJECTS_LINKEDLIST = $(SOURCES_LNKEDLIST:.cpp = .o)
EXECUTABLE_LINKEDLIST = LinkedList-cli
$(EXECUTABLE_LINKEDLIST):
	g++ $(OBJECTS_LINKEDLIST) -o build/$@

#LinkedList-cli
SOURCES_BINARYTREE = /home/krupesh/DataStructures/BinaryTree/main.cpp
OBJECTS_BINARYTREE = $(SOURCES_BINARYTREE:.cpp = .o)
EXECUTABLE_BINARYTREE = BinaryTree-cli
$(EXECUTABLE_BINARYTREE):
	g++ $(OBJECTS_BINARYTREE) -o build/$@
